project_name: cert-manager-webhook-rackspace

builds:
  - main: ./cmd/webhook
    binary: cert-manager-webhook-rackspace
    env:
      - GCO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 'main.Version={{.Version}}'
      - -X 'main.Gitsha={{.ShortCommit}}'

dockers:
  - image_templates:
      - '{{ envOrDefault "REGISTRY" "ghcr.io" }}/{{ envOrDefault "REG_ORG" "rackerlabs" }}/{{ .ProjectName }}:{{ .Version }}-amd64'
    goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.description=Rackspace Cloud DNS support for cert-manager"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
  - image_templates:
      - '{{ envOrDefault "REGISTRY" "ghcr.io" }}/{{ envOrDefault "REG_ORG" "rackerlabs" }}/{{ .ProjectName }}:{{ .Version }}-arm64'
    goos: linux
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.description=Rackspace Cloud DNS support for cert-manager"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"

docker_signs:
  - artifacts: images
    args:
      - "sign"
      - "--yes"
      - "${artifact}"

sboms:
  - id: archive
    artifacts: archive
  - id: binary
    artifacts: binary

docker_manifests:
  - name_template: '{{ envOrDefault "REGISTRY" "ghcr.io" }}/{{ envOrDefault "REG_ORG" "rackerlabs" }}/{{ .ProjectName }}:{{ .Version }}'
    image_templates:
      - '{{ envOrDefault "REGISTRY" "ghcr.io" }}/{{ envOrDefault "REG_ORG" "rackerlabs" }}/{{ .ProjectName }}:{{ .Version }}-amd64'
      - '{{ envOrDefault "REGISTRY" "ghcr.io" }}/{{ envOrDefault "REG_ORG" "rackerlabs" }}/{{ .ProjectName }}:{{ .Version }}-arm64'
  - name_template: '{{ envOrDefault "REGISTRY" "ghcr.io" }}/{{ envOrDefault "REG_ORG" "rackerlabs" }}/{{ .ProjectName }}:latest'
    image_templates:
      - '{{ envOrDefault "REGISTRY" "ghcr.io" }}/{{ envOrDefault "REG_ORG" "rackerlabs" }}/{{ .ProjectName }}:{{ .Version }}-amd64'
      - '{{ envOrDefault "REGISTRY" "ghcr.io" }}/{{ envOrDefault "REG_ORG" "rackerlabs" }}/{{ .ProjectName }}:{{ .Version }}-arm64'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
